/* Toggle between adding and removing the "responsive" class to header when the user clicks on the icon */
function myFunction() {
    var x = document.getElementById("myHeader");
    if (x.className === "header") {
      x.className += " responsive";
    } else {
      x.className = "header";
    }
  }


class ObjectPlant{

	constructor(nameString, biomesStrings, rarityString){
		this.nameString = nameString;
		this.biomesStrings = biomesStrings;
		this.rarityString = rarityString;
	}

}


const plantas = [
	new ObjectPlant("Aeglos",["Forests"],"Uncommon"),
	new ObjectPlant("Alchemilla",["Cities"],"Common"),
	new ObjectPlant("Aldaka",["Forests"],"Uncommon"),
	new ObjectPlant("Alether",["Forests"],"Common"),
	new ObjectPlant("Alfirin",["Deserts"],"Very Rare"),
	new ObjectPlant("Alil",["Deserts"],"Very Rare"),
	new ObjectPlant("Allathorne",["Arctic"],"Common"),
	new ObjectPlant("All-Heale",["Forests"],"Very Common"),
	new ObjectPlant("Aloe",["Cities","Coastal","Deserts"],"Very Common"),
	new ObjectPlant("Alor",["Forests"],"Very Common"),
	new ObjectPlant("Angakara Tree",["Forests"],"Very Rare"),
	new ObjectPlant("Angel's Cactus",["Deserts"],"Uncommon"),
	new ObjectPlant("Angel's Stammerwort",["Forests"],"Very Common"),
	new ObjectPlant("Anserke",["Coastal"],"Common"),
	new ObjectPlant("Arcasa",["Forests"],"Uncommon"),
	new ObjectPlant("Archangelica",["Coastal"],"Common"),
	new ObjectPlant("Arctic Creeper",["Arctic"],"Common"),
	new ObjectPlant("Ardulan",["Arctic","Forests"],"Uncommon"),
	new ObjectPlant("Arkasu",["Deserts"],"Common"),
	new ObjectPlant("Arrowroot",["Deserts"],"Rare"),
	new ObjectPlant("Asarabacca",["Forests"],"Uncommon"),
	new ObjectPlant("Ash",["Forests"],"Common"),
	new ObjectPlant("Ashline",["Forests"],"Uncommon"),
	new ObjectPlant("Ashvein",["Forests"],"Common"),
	new ObjectPlant("Aspen Tree",["Forests"],"Common"),
	new ObjectPlant("Astir",["Forests"],"Common"),
	new ObjectPlant("Astragalus Root",["Forests"],"Uncommon"),
	new ObjectPlant("Atramen",["Coastal"],"Common"),
	new ObjectPlant("Autumn Skullcap",["Forests"],"Rare"),
	new ObjectPlant("Avataer",["Arctic"],"Very Rare"),
	new ObjectPlant("Azure Leaves",["Forests"],"Rare"),
	new ObjectPlant("Balon's Plant",["Deserts"],"Rare"),
	new ObjectPlant("Barberry",["Forests"],"Very Common"),
	new ObjectPlant("Barisc",["Forests"],"Uncommon"),
	new ObjectPlant("Barrelstalk",["Deserts"],"Uncommon"),
	new ObjectPlant("Basil",["Cities","Forests"],"Very Common"),
	new ObjectPlant("Basilisk Breath",["Arctic"],"Very Rare"),
	new ObjectPlant("Bastit",["Deserts"],"Common"),
	new ObjectPlant("Bee Balm",["Arctic"],"Very Common"),
	new ObjectPlant("Belan",["Deserts"],"Very Common"),
	new ObjectPlant("Bija Tree",["Arctic","Forests"],"Rare"),
	new ObjectPlant("Bilberry",["Forests"],"Very Rare"),
	new ObjectPlant("Birthnot",["Arctic"],"Very Common"),
	new ObjectPlant("Bishop's Weed",["Arctic"],"Uncommon"),
	new ObjectPlant("Bison-Gourd",["Forests"],"Common"),
	new ObjectPlant("Bittermourn",["Arctic"],"Legendary"),
	new ObjectPlant("Blackberry",["Forests"],"Very Common"),
	new ObjectPlant("Black Rose",["Forests"],"Common"),
	new ObjectPlant("Bloodbracken",["Forests"],"Very Rare"),
	new ObjectPlant("Bloodgrass",["Forests"],"Common"),
	new ObjectPlant("Bloodspine",["Deserts"],"Common"),
	new ObjectPlant("Bloodstaunch",["Deserts"],"Common"),
	new ObjectPlant("Blueleaf",["Arctic","Forests"],"Very Common"),
	new ObjectPlant("Bodhi Tree",["Cities"],"Rare"),
	new ObjectPlant("Borneas",["Forests"],"Rare"),
	new ObjectPlant("Brelidar",["Arctic"],"Uncommon"),
	new ObjectPlant("Brethil",["Forests"],"Common"),
	new ObjectPlant("Bronzewood",["Forests"],"Common"),
	new ObjectPlant("Butterspice Weed",["Forests"],"Common"),
	new ObjectPlant("Calamus",["Coastal"],"Common"),
	new ObjectPlant("Calacaza Bush",["Deserts"],"Uncommon"),
	new ObjectPlant("Callofex",["Forests"],"Uncommon"),
	new ObjectPlant("Caravara",["Deserts"],"Rare"),
	new ObjectPlant("Cassil",["Forests"],"Very Common"),
	new ObjectPlant("Cat's Tail",["Coastal"],"Very Common"),
	new ObjectPlant("Ceran",["Arctic"],"Very Common"),
	new ObjectPlant("Chromus Slime",["Coastal"],"Very Rare"),
	new ObjectPlant("Cinquefort",["Forests"],"Uncommon"),
	new ObjectPlant("Cline Cactus",["Deserts"],"Uncommon"),
	new ObjectPlant("Coldwood",["Arctic","Forests"],"Common"),
	new ObjectPlant("Constrictor Vine",["Forests"],"Uncommon"),
	new ObjectPlant("Cotsbalm",["Forests"],"Rare"),
	new ObjectPlant("Covadish",["Arctic"],"Very Rare"),
	new ObjectPlant("Cow-Wheat",["Forests"],"Very Common"),
	new ObjectPlant("Crab-Apple",["Cities","Forests"],"Very Common"),
	new ObjectPlant("Crimson Ladies",["Forests"],"Rare"),
	new ObjectPlant("Crisp Chondrus",["Coastal"],"Uncommon"),
	new ObjectPlant("Cubeb",["Forests"],"Common"),
	new ObjectPlant("Culkas",["Coastal"],"Very Common"),
	new ObjectPlant("Culumalda",["Forests"],"Common"),
	new ObjectPlant("Dainaberry",["Forests"],"Common"),
	new ObjectPlant("Darkberry",["Forests"],"Rare"),
	new ObjectPlant("Darkwood",["Arctic"],"Very Rare"),
	new ObjectPlant("Darmanzar Stalk",["Forests"],"Uncommon"),
	new ObjectPlant("Darnell",["Forests"],"Common"),
	new ObjectPlant("Dathlil",["Deserts"],"Very Common"),	
	new ObjectPlant("Deadroot",["Forests"],"Very Rare"),
	new ObjectPlant("Delrean",["Forests"],"Common"),
	new ObjectPlant("Deva's Tears",["Forests"],"Common"),
	new ObjectPlant("Dittany",["Forests"],"Very Common"),
	new ObjectPlant("Djin Blossom",["Deserts"],"Uncommon"),
	new ObjectPlant("Dog Rose",["Forests"],"Very Common"),
	new ObjectPlant("Draaf",["Coastal"],"Very Common"),
	new ObjectPlant("Dragon's Breath",["Arctic"],"Common"),
	new ObjectPlant("Dragon-Eye Oak",["Forests"],"Uncommon"),
	new ObjectPlant("Dragonspine",["Deserts"],"Uncommon"),
	new ObjectPlant("Dragontears",["Deserts"],"Very Rare"),
	new ObjectPlant("Duskwood",["Forests"],"Common"),
	new ObjectPlant("Dwarf Hops",["Cities","Forests"],"Very Common"),
	new ObjectPlant("Dwarven Oak",["Forests"],"Rare"),
	new ObjectPlant("Ecru",["Coastal"],"Rare"),
	new ObjectPlant("Edelwood",["Forests"],"Very Rare"),
	new ObjectPlant("Eldaas",["Arctic"],"Very Common"),
	new ObjectPlant("Elder Tree",["Forests"],"Very Common"),
	new ObjectPlant("Elm",["Forests"],"Very Common"),
	new ObjectPlant("Elven Willow",["Forests"],"Very Common"),
	new ObjectPlant("Elvish Galingale",["Forests"],"Very Common"),
	new ObjectPlant("Ember Root",["Coastal","Forests"],"Common"),
	new ObjectPlant("Entriste",["Deserts"],"Uncommon"),
	new ObjectPlant("Ephedra",["Deserts"],"Rare"),
	new ObjectPlant("Falsifal",["Forests"],"Common"),
	new ObjectPlant("Febfendu",["Forests"],"Very Rare"),
	new ObjectPlant("Felmather",["Coastal"],"Rare"),
	new ObjectPlant("Felsul",["Forests"],"Rare"),
	new ObjectPlant("Fennel Silk",["Arctic"],"Common"),
	new ObjectPlant("Fey Cherry",["Forests"],"Very Rare"),
	new ObjectPlant("Firethorn",["Coastal"],"Rare"),
	new ObjectPlant("Footleaf",["Arctic"],"Uncommon"),
	new ObjectPlant("Foxglove",["Cities","Forests"],"Very Common"),
	new ObjectPlant("Fumitore",["Forests"],"Uncommon"),
	new ObjectPlant("Fuiyáru",["Forests"],"Rare"),
	new ObjectPlant("Gallowbrush",["Forests"],"Uncommon"),
	new ObjectPlant("Gardenflax",["Cities","Forests"],"Very Rare"),
	new ObjectPlant("Gariig",["Coastal","Deserts"],"Legendary"),
	new ObjectPlant("Gefnul",["Arctic"],"Legendary"),
	new ObjectPlant("Ginyak Weed",["Cities"],"Common"),
	new ObjectPlant("Grim Flowers",["Cities"],"Common"),
	new ObjectPlant("Goat's Rue",["Forests"],"Very Common"),
	new ObjectPlant("Goblin Rogue",["Forests"],"Very Common"),
	new ObjectPlant("Goldencup",["Arctic"],"Rare"),
	new ObjectPlant("Goldenweb",["Forests"],"Uncommon"),
	new ObjectPlant("Golden Coin Cactus",["Deserts"],"Very Common"),
	new ObjectPlant("Golden Crown",["Forests"],"Very Common"),
	new ObjectPlant("Golden Desert Tree",["Deserts"],"Rare"),
	new ObjectPlant("Golden Lungwort",["Forests"],"Uncommon"),
	new ObjectPlant("Grendar",["Arctic"],"Very Common"),
	new ObjectPlant("Gulthias Tree",["Forests"],"Legendary"),
	new ObjectPlant("Haella",["Cities"],"Uncommon"),
	new ObjectPlant("Halcyon Crocus",["Arctic"],"Legendary"),
	new ObjectPlant("Halfling Thistle",["Forests"],"Rare"),
	new ObjectPlant("Hands of Laretha",["Forests"],"Rare"),
	new ObjectPlant("Hangman Tree",["Forests"],"Rare"),
	new ObjectPlant("Hara'dan",["Deserts"],"Uncommon"),
	new ObjectPlant("Hara'den",["Deserts"],"Uncommon"),
	new ObjectPlant("Hare's Ear",["Arctic"],"Very Common"),
	new ObjectPlant("Harfy",["Coastal"],"Very Common"),
	new ObjectPlant("Harlequin's Harp",["Cities","Coastal"],"Very Common"),
	new ObjectPlant("Harpy Nest",["Forests"],"Common"),
	new ObjectPlant("Hart's Crown",["Forests"],"Rare"),
	new ObjectPlant("Hate Gartlet",["Forests"],"Common"),
	new ObjectPlant("Hawkweed",["Forests"],"Uncommon"),
	new ObjectPlant("Healing Apple Tree",["Forests"],"Common"),
	new ObjectPlant("Healwell",["Cities"],"Very Common"),
	new ObjectPlant("Hidden Hibiscus",["Forests"],"Very Rare"),
	new ObjectPlant("Hiexel",["Forests"],"Common"),
	new ObjectPlant("Hiljirat Pepper",["Forests"],"Uncommon"),
	new ObjectPlant("Hoggle Beans",["Arctic"],"Very Common"),
	new ObjectPlant("Hydrathistle",["Coastal"],"Uncommon"),
	new ObjectPlant("Hyperia",["Forests"],"Very Rare"),
	new ObjectPlant("Ice Lotus",["Arctic"],"Rare"),
	new ObjectPlant("Iceflower",["Arctic"],"Uncommon"),
	new ObjectPlant("Inari",["Deserts"],"Very Common"),
	new ObjectPlant("Iraster",["Forests"],"Very Rare"),
	new ObjectPlant("Ironhard",["Forests"],"Rare"),
	new ObjectPlant("Jaffray",["Forests"],"Common"),
	new ObjectPlant("Jojopojo",["Arctic"],"Uncommon"),
	new ObjectPlant("Juniper",["Cities","Forests"],"Very Common"),
	new ObjectPlant("Juzam",["Deserts"],"Very Rare"),
	new ObjectPlant("Kae'la",["Forests"],"Rare"),
	new ObjectPlant("Kanishta",["Arctic"],"Uncommon"),
	new ObjectPlant("Karat",["Coastal"],"Very Common"),
	new ObjectPlant("Karcatta Brambles",["Deserts"],"Uncommon"),
	new ObjectPlant("Kathkusa",["Arctic"],"Very Rare"),
	new ObjectPlant("Kelventari",["Deserts"],"Very Rare"),
	new ObjectPlant("Kieros",["Forests"],"Rare"),
	new ObjectPlant("Kilmakur",["Forests"],"Rare"),
	new ObjectPlant("King's Pear",["Forests"],"Common"),
	new ObjectPlant("Kingsfruit",["Forests"],"Very Rare"),
	new ObjectPlant("Klagul",["Arctic"],"Legendary"),
	new ObjectPlant("Kylathar",["Forests"],"Legendary"),
	new ObjectPlant("Laishaberries",["Forests"],"Common"),
	new ObjectPlant("Lakeleaf",["Coastal"],"Uncommon"),
	new ObjectPlant("Larnurma",["Forests"],"Very Common"),
	new ObjectPlant("Laspar",["Forests"],"Very Common"),
	new ObjectPlant("Leopard's Bane",["Forests"],"Very Common"),
	new ObjectPlant("Linden Tree",["Cities","Forests"],"Very Common"),
	new ObjectPlant("Lish",["Forests"],"Uncommon"),
	new ObjectPlant("Lissuin",["Deserts"],"Rare"),
	new ObjectPlant("Livewood",["Forests"],"Very rare"),
	new ObjectPlant("Lizard Eaters",["Cities"],"Very Common"),
	new ObjectPlant("Locust Needle",["Coastal","Forests"],"Very Common"),
	new ObjectPlant("Longinal Leaf",["Cities"],"Common"),
	new ObjectPlant("Lordinberry",["Forests"],"Very Rare"),
	new ObjectPlant("Luhix",["Forests"],"Uncommon"),
	new ObjectPlant("Lumina Cap",["Cities"],"Rare"),
	new ObjectPlant("Maiden's Hair",["Forests"],"Very Rare"),
	new ObjectPlant("Maitake Mushroom",["Forests"],"Very Common"),
	new ObjectPlant("Maracan",["Deserts"],"Very Rare"),
	new ObjectPlant("Marjoram",["Cities"],"Very Common"),
	new ObjectPlant("Mar'kerlan",["Forests"],"Rare"),
	new ObjectPlant("Marigold",["Forests"],"Very Common"),
	new ObjectPlant("Maruera",["Forests"],"Rare"),
	new ObjectPlant("Megillos",["Cities"],"Common"),
	new ObjectPlant("Mirenna",["Forests"],"Rare"),
	new ObjectPlant("Mistletoe",["Arctic","Forests"],"Very Common"),
	new ObjectPlant("Mokodo Bush",["Cities"],"Very Rare"),
	new ObjectPlant("Mountain Garlic",["Coastal"],"Common"),
	new ObjectPlant("Myrthis",["Forests"],"Common"),
	new ObjectPlant("Navew",["Cities"],"Uncommon"),
	new ObjectPlant("Nordra",["Deserts"],"Very Common"),
	new ObjectPlant("Northlinch",["Cities"],"Very Common"),
	new ObjectPlant("Novanor",["Deserts"],"Uncommon"),
	new ObjectPlant("Obaddis Leaf",["Arctic"],"Rare"),
	new ObjectPlant("Orticusp",["Forests"],"Very Rare"),
	new ObjectPlant("Oruighen",["Deserts"],"Uncommon"),
	new ObjectPlant("Osira",["Forests"],"Common"),
	new ObjectPlant("Peony",["Cities"],"Common"),
	new ObjectPlant("Periwinkle",["Cities"],"Very Common"),
	new ObjectPlant("Powdered Desert Milk",["Desert"],"Uncommon"),
	new ObjectPlant("Psyllium",["Cities"],"Very Common"),
	new ObjectPlant("Purple Pipeweed",["Cities"],"Uncommon"),
	new ObjectPlant("Quickweed",["Coastal"],"Common"),
	new ObjectPlant("Quivar",["Arctic"],"Rare"),
	new ObjectPlant("Redroot",["Cities"],"Uncommon"),
	new ObjectPlant("Rose Campion",["Desert"],"Very Rare"),
	new ObjectPlant("Rouddan",["Arctic"],"Rare"),
	new ObjectPlant("Sabito",["Coastal"],"Uncommon"),
	new ObjectPlant("Salamander Orchids",["Arctic","Cities"],"Rare"),
	new ObjectPlant("Sand Vine",["Coastal"],"Uncommon"),
	new ObjectPlant("Sandberry Bush",["Desert"],"Very Common"),
	new ObjectPlant("Sasami Tree",["Cities"],"Very Rare"),
	new ObjectPlant("Scented Mayweed",["Arctic"],"Common"),
	new ObjectPlant("Scholar's Dream",["Cities"],"Rare"),
	new ObjectPlant("Sessali",["Coastal"],"Uncommon"),
	new ObjectPlant("Sinquoi",["Desert"],"Very Rare"),
	new ObjectPlant("Sleeping Ivy",["Coastal"],"Common"),
	new ObjectPlant("Snowflake Lichen",["Arctic"],"Uncommon"),
	new ObjectPlant("Snowwood",["Arctic"],"Uncommon"),
	new ObjectPlant("Stonestream",["Arctic"],"Very Rare"),
	new ObjectPlant("Strawberry",["Cities"],"Very Common"),
	new ObjectPlant("Surane",["Coastal"],"Uncommon"),
	new ObjectPlant("Swordstalks",["Desert"],"Very Rare"),
	new ObjectPlant("Tansy",["Cities"],"Very Common"),
	new ObjectPlant("Taran'ka",["Desert"],"Common"),
	new ObjectPlant("Tateesha",["Desert"],"Rare"),
	new ObjectPlant("Tereeka Root",["Coastal"],"Rare"),
	new ObjectPlant("Thalsen Weed",["Arctic"],"Very Common"),
	new ObjectPlant("Thir",["Arctic"],"Very Common"),
	new ObjectPlant("Thistledown",["Arctic"],"Very Rare"),
	new ObjectPlant("Thurl",["Desert"],"Very Common"),
	new ObjectPlant("Thyme",["Cities"],"Very Common"),
	new ObjectPlant("Umozokai Flower",["Coastal","Desert"],"Very Common"),
	new ObjectPlant("Verdant Goeleth",["Cities"],"Very Rare"),
	new ObjectPlant("Vodare",["Cities"],"Rare"),
	new ObjectPlant("Waterorb",["Coastal"],"Common"),
	new ObjectPlant("Werasa",["Cities"],"Common"),
	new ObjectPlant("Whistling Cactus",["Desert"],"Uncommon"),
	new ObjectPlant("Ylam Tree",["Desert"],"Very Rare"),
	new ObjectPlant("Zulsendra",["Arctic"],"Very Rare"),
	new ObjectPlant("",[""],"")
];


function PlantRandomizer() {
      // Obtener el bioma y dado ingresado por el jugador
      var biomeInput = document.getElementById('idBiome').value;
					var diceInput = parseInt(document.getElementById('idDice').value);

					const plantBiome = plantas.filter((planta) => planta.biomesStrings.includes(biomeInput));

					let plantBiomeRarity = [];
					if (diceInput >= 1 && diceInput <= 55){
						plantBiomeRarity = plantBiome.filter((planta) => planta.rarityString == "Very Common")
					}
					else if (diceInput >= 56 && diceInput <= 81){
						plantBiomeRarity = plantBiome.filter((planta) => planta.rarityString == "Common")
					}
					else if (diceInput >= 82 && diceInput <= 93){
						plantBiomeRarity = plantBiome.filter((planta) => planta.rarityString == "Uncommon")
					}
					else if (diceInput >= 94 && diceInput <= 98){
						plantBiomeRarity = plantBiome.filter((planta) => planta.rarityString == "Rare")
					}
					else if (diceInput == 99){
						plantBiomeRarity = plantBiome.filter((planta) => planta.rarityString == "Very Rare")
					}
					else if (diceInput == 100){
						plantBiomeRarity = plantBiome.filter((planta) => planta.rarityString == "Legendary" && plantBiome.filter((planta) => planta.rarityString == "very Rare")
					}

					var plantafinal = Math.floor(Math.random() * plantBiomeRarity.length);
	
      // Mostrar el resultado en el párrafo con id "plantaObtenida"
      document.getElementById('plantaObtenida').textContent = plantBiomeRarity[plantafinal].nameString;
}
